import type { Metadata } from 'next'
import { radio_canada, poppins } from '@/atoms/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${radio_canada.variable}`}>
      <body className="font-poppins">
        <main className="min-h-screen w-full font-poppins">{children}</main>
      </body>
    </html>
  )
}
